// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLUgeoGtAag-pYGjAYtbRdSiH4_FeNcC8',
    appId: '1:428737400126:web:e342772351629ab58cb06f',
    messagingSenderId: '428737400126',
    projectId: 'shoppingapp-a4ee9',
    authDomain: 'shoppingapp-a4ee9.firebaseapp.com',
    storageBucket: 'shoppingapp-a4ee9.firebasestorage.app',
    measurementId: 'G-3LKQEN0BJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF11olJRn1N3TT4UKi-eZGcsT5_j8cU-U',
    appId: '1:428737400126:android:d23a8ca8f426d6708cb06f',
    messagingSenderId: '428737400126',
    projectId: 'shoppingapp-a4ee9',
    storageBucket: 'shoppingapp-a4ee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBko_rTVWl-mLSG_kw0HBN5Pd283pjKSVs',
    appId: '1:428737400126:ios:ac5fb042acb984678cb06f',
    messagingSenderId: '428737400126',
    projectId: 'shoppingapp-a4ee9',
    storageBucket: 'shoppingapp-a4ee9.firebasestorage.app',
    androidClientId: '428737400126-69g6snhnl25s2rq5bk4gk2337s8cb05i.apps.googleusercontent.com',
    iosClientId: '428737400126-85ld5vms0r5vdesvl839h4optusejikn.apps.googleusercontent.com',
    iosBundleId: 'com.kashyapapp.shoppingApp',
  );

}